CREATE DATABASE HR;
USE HR;

CREATE TABLE FUNCIONARIO (
   CODIGO         INT PRIMARY KEY AUTO_INCREMENT,
   NOME           VARCHAR (255)   NOT NULL,
   SALARIO        NUMERIC  (10,2)  DEFAULT 1000.00);